## NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt,....

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors. 

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [20]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [21]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [22]:
# we can create numpy arrays by converting lists
# this is a vector

vec = np.array([1,2,3])
print(vec)

# we can create matrices by converting list of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T) # Tranpose of a matrix.



[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [23]:
# There are lots of other ways to create numpy arrays

vec2 = np.arange(0,15) # Starting point is inclusive and stopping point is exclusive. 
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [24]:
vec4 = np.linspace(0,5,10) # Starting and stopping point is inclusive. Th
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [25]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [39]:
# We can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))


[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [43]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)


[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [44]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [45]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [46]:
# we can also use numpy to generate samples of a random variable 
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5)
print('')
print(rand_mat2)

[[0.39166524 0.65295273 0.24886025 0.58484499 0.37592235]
 [0.45907708 0.25998202 0.55726437 0.73713978 0.51418766]
 [0.41544714 0.50319037 0.6364731  0.98652826 0.54570721]
 [0.28488493 0.76360115 0.374085   0.27265591 0.73162431]
 [0.82732119 0.21893175 0.91906624 0.22071339 0.05503151]]

[[-0.86577719 -1.2117954   0.01194825 -0.48691997 -0.69378486]
 [ 0.5913213   0.80167524 -0.41115336  1.02486101 -0.84599809]
 [-0.3058551   2.573055   -0.51724946  0.18385722 -0.50492562]
 [ 0.83778511 -1.44752318  0.8474593   0.95675348 -0.45575045]
 [ 1.35432352 -2.27535422  0.47525247 -0.0978734  -0.41514409]
 [ 1.16504926  1.93385501  2.29122123 -0.7282129  -0.38963196]
 [ 1.05275725 -0.84668639  1.66524625 -0.46062527  1.87593339]
 [ 1.89180411 -1.02920826  0.69797619 -1.43956346  0.97915214]
 [-0.43354031 -3.41425455  1.37074539  0.75546457 -0.62143296]
 [-0.86411441 -1.37289976  0.81659796 -0.01090444 -0.04549121]]


In [47]:
# we can also use numpy for statistical tools on arrays 
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5014863173579497
1.186377572318343


In [48]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.05503150650526589
2.5730549959581412


In [49]:
# How do we access entries in a numpy vector.

rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.72767813e+00  7.45854074e-01  5.56920694e-01  1.60388559e+00
  1.88839527e+00 -1.17247954e+00  8.44794607e-01  5.05640011e-02
  6.91239019e-02  1.10838231e+00  2.32415267e-02  1.19699647e+00
  1.74998180e-03 -3.05856037e-01  8.67674954e-01  2.18818850e-01
 -2.12882889e-02 -2.94544086e-01 -4.97996954e-01]
0.8447946072174229


In [50]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 1.88839527 -1.17247954  0.84479461  0.050564    0.0691239 ]


In [51]:
# we can also access multiple non-consecutive entries using np.arange

print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.72767813  1.60388559  0.84479461  1.10838231  0.00174998]


In [52]:
rand_mat = np.random.rand(2,3)

In [53]:
# what about matrices

print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.99799875 0.6517647  0.89574488]
 [0.53385899 0.05875206 0.70121459]]
0.701214589282154
0.701214589282154


In [54]:
print(rand_mat[0:2,1:3])

[[0.6517647  0.89574488]
 [0.05875206 0.70121459]]


In [55]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.72767813e+00  7.45854074e-01  5.56920694e-01  1.60388559e+00
  1.88839527e+00 -1.17247954e+00  8.44794607e-01  5.05640011e-02
  6.91239019e-02  1.10838231e+00  2.32415267e-02  1.19699647e+00
  1.74998180e-03 -3.05856037e-01  8.67674954e-01  2.18818850e-01
 -2.12882889e-02 -2.94544086e-01 -4.97996954e-01]

[-1.72767813e+00  7.45854074e-01  5.56920694e-01  4.00000000e+00
  4.00000000e+00 -1.17247954e+00  8.44794607e-01  5.05640011e-02
  6.91239019e-02  1.10838231e+00  2.32415267e-02  1.19699647e+00
  1.74998180e-03 -3.05856037e-01  8.67674954e-01  2.18818850e-01
 -2.12882889e-02 -2.94544086e-01 -4.97996954e-01]

[-1.72767813e+00  7.45854074e-01  5.56920694e-01  1.00000000e+00
  2.00000000e+00 -1.17247954e+00  8.44794607e-01  5.05640011e-02
  6.91239019e-02  1.10838231e+00  2.32415267e-02  1.19699647e+00
  1.74998180e-03 -3.05856037e-01  8.67674954e-01  2.18818850e-01
 -2.12882889e-02 -2.94544086e-01 -4.97996954e-01]


In [56]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.99799875 0.6517647  0.89574488]
 [0.53385899 0.05875206 0.70121459]]

[[0.99799875 0.6517647  0.89574488]
 [0.53385899 0.05875206 0.70121459]]


In [57]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[0.99799875 0.6517647  0.89574488]
 [0.53385899 0.05875206 0.70121459]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [58]:
print(rand_mat)

[[3. 3. 3.]
 [3. 3. 3.]]


In [59]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat[:] = 99
print(sub_mat2)
print(rand_mat)

[[3. 3. 3.]
 [3. 3. 3.]]
[[99. 99. 99.]
 [99. 99. 99.]]


In [60]:
# we can also access entries with logicals 
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.65698772 -0.01725662 -0.11131758 -1.09282705 -0.58241031  0.0425171
  1.32461457 -0.61008993  0.14333713  0.41334481  0.28898363  1.5895617
 -0.71250939  0.08076517 -0.93352287]
[False False False False False  True  True False  True  True  True  True
 False  True False]
[0.0425171  1.32461457 0.14333713 0.41334481 0.28898363 1.5895617
 0.08076517]


In [61]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.86577719 -1.2117954   0.01194825 -0.48691997 -0.69378486]
 [ 0.5913213   0.80167524 -0.41115336  1.02486101 -0.84599809]
 [-0.3058551   2.573055   -0.51724946  0.18385722 -0.50492562]
 [ 0.83778511 -1.44752318  0.8474593   0.95675348 -0.45575045]
 [ 1.35432352 -2.27535422  0.47525247 -0.0978734  -0.41514409]
 [ 1.16504926  1.93385501  2.29122123 -0.7282129  -0.38963196]
 [ 1.05275725 -0.84668639  1.66524625 -0.46062527  1.87593339]
 [ 1.89180411 -1.02920826  0.69797619 -1.43956346  0.97915214]
 [-0.43354031 -3.41425455  1.37074539  0.75546457 -0.62143296]
 [-0.86411441 -1.37289976  0.81659796 -0.01090444 -0.04549121]]
[0.01194825 0.5913213  0.80167524 1.02486101 2.573055   0.18385722
 0.83778511 0.8474593  0.95675348 1.35432352 0.47525247 1.16504926
 1.93385501 2.29122123 1.05275725 1.66524625 1.87593339 1.89180411
 0.69797619 0.97915214 1.37074539 0.75546457 0.81659796]


In [62]:
print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.65698772 -0.01725662 -0.11131758 -1.09282705 -0.58241031  0.0425171
  1.32461457 -0.61008993  0.14333713  0.41334481  0.28898363  1.5895617
 -0.71250939  0.08076517 -0.93352287]

[-0.65698772 -0.01725662 -0.11131758 -1.09282705 -0.58241031  0.0425171
 -5.         -0.61008993  0.14333713  0.41334481  0.28898363 -5.
 -0.71250939  0.08076517 -0.93352287]


In [63]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)

In [64]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [65]:
# now let's load it 
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.86577719 -1.2117954   0.01194825 -0.48691997 -0.69378486]
 [ 0.5913213   0.80167524 -0.41115336  1.02486101 -0.84599809]
 [-0.3058551   2.573055   -0.51724946  0.18385722 -0.50492562]
 [ 0.83778511 -1.44752318  0.8474593   0.95675348 -0.45575045]
 [ 1.35432352 -2.27535422  0.47525247 -0.0978734  -0.41514409]
 [ 1.16504926  1.93385501  2.29122123 -0.7282129  -0.38963196]
 [ 1.05275725 -0.84668639  1.66524625 -0.46062527  1.87593339]
 [ 1.89180411 -1.02920826  0.69797619 -1.43956346  0.97915214]
 [-0.43354031 -3.41425455  1.37074539  0.75546457 -0.62143296]
 [-0.86411441 -1.37289976  0.81659796 -0.01090444 -0.04549121]]



In [66]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array = loaded_zip['rand_mat']
print(new_array)

[[99. 99. 99.]
 [99. 99. 99.]]

[[-0.86577719 -1.2117954   0.01194825 -0.48691997 -0.69378486]
 [ 0.5913213   0.80167524 -0.41115336  1.02486101 -0.84599809]
 [-0.3058551   2.573055   -0.51724946  0.18385722 -0.50492562]
 [ 0.83778511 -1.44752318  0.8474593   0.95675348 -0.45575045]
 [ 1.35432352 -2.27535422  0.47525247 -0.0978734  -0.41514409]
 [ 1.16504926  1.93385501  2.29122123 -0.7282129  -0.38963196]
 [ 1.05275725 -0.84668639  1.66524625 -0.46062527  1.87593339]
 [ 1.89180411 -1.02920826  0.69797619 -1.43956346  0.97915214]
 [-0.43354031 -3.41425455  1.37074539  0.75546457 -0.62143296]
 [-0.86411441 -1.37289976  0.81659796 -0.01090444 -0.04549121]]
[[99. 99. 99.]
 [99. 99. 99.]]


In [67]:
# We can also save/load as text files... but only single variables.
np.savetxt('text_file_name.txt',rand_mat, delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter = ',')
print('')
print(rand_mat_txt)


[[99. 99. 99.]
 [99. 99. 99.]]
